"""Generate tunnel_cfg.h for tunnel mode bypass.exe
Usage: python gen_tunnel_cfg.py <tunnel_server_ip> [register_port]
  tunnel_server_ip = IP of the machine running tunnel_server.py
  register_port    = port for target to register (default 5555)
"""
import sys

def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    ip = sys.argv[1]
    port = int(sys.argv[2]) if len(sys.argv) > 2 else 5555
    parts = ip.split(".")
    if len(parts) != 4 or not all(p.isdigit() for p in parts):
        print(f"[-] Invalid IP: {ip}"); sys.exit(1)
    content = (
        f"// Auto-generated by gen_tunnel_cfg.py\n"
        f"#ifndef TUNNEL_CFG_H\n#define TUNNEL_CFG_H\n"
        f"#define TUNNEL_SERVER_IP {{{parts[0]},{parts[1]},{parts[2]},{parts[3]}}}\n"
        f"#define TUNNEL_SERVER_PORT {port}\n"
        f"#endif\n"
    )
    with open("tunnel_cfg.h", "w") as f:
        f.write(content)
    print(f"[+] tunnel_cfg.h: tunnel server {ip}:{port}")

if __name__ == "__main__":
    main()
