#!/usr/bin/env python3
"""
gen_frpc_config.py — 生成 frpc.toml 配置文件
================================================
用法:
    python gen_frpc_config.py <VPS_IP> <remote_port> <local_port>

输出:
    frpc.toml — 可直接给 frpc 使用
    或配合 embed_frp.py 加密后嵌入

示例:
    python gen_frpc_config.py 123.45.67.89 4444 4444
"""

import sys

def generate_config(vps_ip: str, remote_port: int, local_port: int) -> str:
    return f"""# frpc.toml — Auto-generated by gen_frpc_config.py
serverAddr = "{vps_ip}"
serverPort = 7000
loginFailExit = false

[[proxies]]
name = "shell_tunnel"
type = "tcp"
localIP = "127.0.0.1"
localPort = {local_port}
remotePort = {remote_port}
"""

def main():
    if len(sys.argv) < 3:
        print("Usage: python gen_frpc_config.py <VPS_IP> <remote_port> [local_port]")
        print("  Example: python gen_frpc_config.py 123.45.67.89 4444 4444")
        sys.exit(1)

    vps_ip = sys.argv[1]
    remote_port = int(sys.argv[2])
    local_port = int(sys.argv[3]) if len(sys.argv) > 3 else remote_port

    config = generate_config(vps_ip, remote_port, local_port)

    with open("frpc.toml", "w", encoding="utf-8") as f:
        f.write(config)

    print(f"[+] Generated frpc.toml")
    print(f"    VPS:         {vps_ip}:7000")
    print(f"    Tunnel:      VPS:{remote_port} → localhost:{local_port}")
    print(f"    Output:      frpc.toml ({len(config)} bytes)")

if __name__ == "__main__":
    main()
