Start-Process powershell -Verb RunAs -ArgumentList "-Command ",
"Write-Output '=== Restoring UAC ===';",
"Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name EnableLUA -Value 1 -Type DWord;",
"Write-Output '=== Removing Run key ===';",
"Remove-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name WindowsUpdate -ErrorAction SilentlyContinue;",
"Write-Output '=== Cleaning up files ===';",
"$appd = [Environment]::GetFolderPath('ApplicationData');",
"$caches = Join-Path $appd 'Microsoft\Windows\Caches';",
"if (Test-Path $caches) { Remove-Item -Recurse -Force $caches; Write-Output 'Removed Caches folder' }",
"$bakPath = Join-Path $env:TEMP '..\Desktop\WindowsUpdate.exe.bak' 2>`$null;",
"$bak = Get-ChildItem -Path $env:USERPROFILE -Filter 'WindowsUpdate.exe.bak' -Recurse -ErrorAction SilentlyContinue | Select -First 1;",
"if ($bak) { Move-Item $bak.FullName ([System.IO.Path]::ChangeExtension($bak.FullName, '.exe')) -Force; Write-Output 'Restored backup' }",
"Write-Output '=== UAC requires reboot to take full effect ===';",
"Read-Host 'Press Enter to exit'"
